# Generated by Django 4.1 on 2022-08-08 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_operaions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
