# Generated by Django 4.1 on 2022-08-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_operations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='operations',
        ),
    ]
